# Generated by Django 6.0.4 on 2026-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(default="stable_document.txt", max_length=255),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="The row or paragraph number"),
                ),
                ("content", models.TextField(help_text="The raw text of the chunk")),
            ],
        ),
    ]
