# Generated by Django 6.0.4 on 2026-04-09 11:00

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., BİRİNCİ BÖLÜM", max_length=255),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="The AI mathematical representation of the text",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="madde",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="chunk_index",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="document_name",
            field=models.CharField(default="KVKK.pdf", max_length=255),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="intelligence.documentsection",
            ),
        ),
    ]
