# Generated by Django 6.0.4 on 2026-04-09 11:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_documentsection_documentchunk_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=384,
                help_text="The AI mathematical representation of the text",
                null=True,
            ),
        ),
    ]
