# Generated by Django 6.0.4 on 2026-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0005_documentchunk_madde_to_integer"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="madde_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
