# Generated by Django 6.0.4 on 2026-04-17 08:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0006_documentchunk_add_madde_title"),
    ]

    operations = [
        # pgvector cannot ALTER a vector column's dimensions while existing rows
        # have vectors of the old size. We must NULL them out first, then retype.
        migrations.RunSQL(
            sql="UPDATE intelligence_documentchunk SET embedding = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1024,
                help_text="The AI mathematical representation of the text",
                null=True,
            ),
        ),
    ]
