# Generated by Django 6.0.4 on 2026-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0007_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("sources", models.JSONField(default=list)),
                (
                    "rating",
                    models.CharField(
                        choices=[("good", "👍 Good"), ("bad", "👎 Bad")], max_length=10
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
