# Generated by Django 6.0.4 on 2026-04-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0010_add_chat_session_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="regime",
            field=models.CharField(
                choices=[("tr", "Turkish"), ("eu", "European Union")],
                db_index=True,
                default="tr",
                max_length=10,
            ),
        ),
    ]
